name: examples
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - windows
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
   
      - name: Prepare
        run: |
            mkdir _deploy
            cp -R examples _deploy
            cp -R demos/angular-app/dist/angular-app _deploy/angular-app
            cp -R demos/react-app/build _deploy/react-app
            cp -R demos/svelte-app/build _deploy/svelte-app
      - name: Append Analytics
        run: |
            node scripts/append-ga.cjs _deploy/examples
            node scripts/append-ga.cjs _deploy/react-app
            node scripts/append-ga.cjs _deploy/angular-app
            node scripts/append-ga.cjs _deploy/svelte-app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _deploy
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
