name: examples
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - windows
permissions:
  contents: read
  pages: write
  id-token: write
environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}
     steps:
     - name: Checkout Repo
     uses: actions/checkout@v3
     - name:  Setup Node 18
    uses: actions/setup-node@v2
    with:
      node-version: "18"
      
  - name: Prepare
    # ...

  - name: Append Analytics
    # ...

  - name: Upload artifact
    uses: actions/upload-pages-artifact@v1
    with:
      path: _deploy

  - name: Deploy
    id: deployment
    uses: actions/deploy-pages@v1
Requested labels: windows
